version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '5001:5001'
    environment:
      - MONGO_URI=your_mongo_db_uri
      - JWT_SECRET=your_jwt_secret

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'

